language: python
python: 3.8
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - python --version
  - python tests.py # from https://github.com/bhargavvader/pycobra/
  - coverage
  # - cd docs && make html && make doctest SPHINXOPTS=-W #Make doctest treat warnings as errors, to detect problems in autodoc
after_success:
  - coveralls